version: '3.1'

networks:
  backend:
    driver: "bridge"
  frontend:
    driver: "bridge"

services:

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/sites:/etc/nginx/sites-enabled/
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/nginxconfig.io:/etc/nginx/nginxconfig.io
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      #- /etc/letsencrypt/archive/silvain.eu/:/certs:ro

      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - frontend

  wordpress:
    image: wordpress:php7.4-fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: AdminDeLaBase
      WORDPRESS_DB_PASSWORD: MotDePasseDeAdminDeLaBase
      WORDPRESS_DB_NAME: site_vitrine
      DISALLOW_FILE_EDIT: "true"
    volumes:
      - wordpress:/var/www/html

    depends_on:
      - db
    networks:
      - backend
      - frontend

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: site_vitrine
      MYSQL_USER: AdminDeLaBase
      MYSQL_PASSWORD: MotDePasseDeAdminDeLaBase
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

volumes:
  wordpress:
  db: